data:
    target: ["AC"]
    source: ["HQ"]
    segs: ["AC"]
    down_sample: 1
    patch_size: [64, 64, 16]
hyperparameters:
    img_dims: [64, 64, 16]
augmentation:
    depth: 16
    flip_prob: 0.5 # Settings for standard augmentation
    rotation: 45.0
    scale: [0.8, 1.6]
    shear: 15.0
    translate: [0.25, 0.25]
    colour: true # Settings for differentiable augmentation
    translation: true
    cutout: true