name: multi-phase
channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - pip=22.2.2
  - python=3.8
  - black
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - flake8
  - isort
  - matplotlib>=3.4
  - mypy
  - pytest>=7.1.2
  - pyyaml=6.0
  - simpleitk>=2.1
  - tensorflow-gpu=2.3.0
  - tox
  