name: multi-phase
channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - pip=22.2
  - python=3.8
  - black=22.6.0
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - flake8=6.0.0
  - isort=5.9.3
  - matplotlib>=3.4
  - mypy=0.981
  - pre-commit=2.20.0
  - pytest>=7.1.2
  - pyyaml=6.0
  - simpleitk>=2.1
  - tensorflow-gpu=2.3.0
  - tox=4.3.5
  