name: contrast
channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - pip=22.2.2
  - python=3.10
  - black
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - flake8
  - isort
  - matplotlib>=3.4
  - mypy
  - pytest>=7.1.2
  - pyyaml=6.0
  - simpleitk>=2.1
  - tox
  - pip:
    - tensorflow==2.9.1
    - -e ../common
    - -e .